services:
  webui:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.webui
    ports:
      - "3000:80"
    environment:
      - VITE_APP_ENV=local
    depends_on:
      - api
    networks:
      - gofannon-net

  api:
    build:
      context: ../../packages/api/user-service
      dockerfile: ../../../infra/docker/Dockerfile.api
    volumes:
      - ../../packages/api/user-service:/app # Mount for hot-reloading
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - STORAGE_PROVIDER=s3
      - S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=us-east-1
    env_file:
      - ./.env
    depends_on:
      - minio
    networks:
      - gofannon-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - gofannon-net
    command: server /data --console-address ":9001"

  

networks:
  gofannon-net:
    driver: bridge

volumes:
  minio-data: